### ISSUE TITLE
How can I manually add a new search engine?

### ISSUE THREAD

**Issue by chenhuiChang** [smarkm/soox#1]
For example, I want to add jquery lib. Can I change it by my self?

**Comment by smarkm** [comment]
@chenhuiChang You means search jquery lib ? The function that manually add new search engines will be provide by next version, and you can hack the code by yourself to add new engines. If you are in eclipse see [code ](https://github.com/smarkm/soox/blob/master/eclipse/org.smark.soox.eclipse/src/org/smark/soox/eclipse/handlers/SooxSearchHandler.java), and if you are in vscode see [code](https://github.com/smarkm/soox/blob/master/vscode/soox.js) .

**Comment by chenhuiChang** [comment]
I got it! Thank you.
I can edit the search engines by myself now.
